spring:
    datasource:
        url: "jdbc:postgresql://localhost:5432/cloud_storage_db"
        username: "postgres"
        password: "123"
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true